language: python
python:
  - 2.6
  - 2.7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postfix
  - echo 'smtpd_sender_restrictions = regexp:/etc/postfix/sender_restriction' | sudo tee /etc/postfix/main.cf
  - sudo cp .travis/postfix/sender_restriction /etc/postfix/
  - sudo cp samples/* /var/spool/postfix/hold/
install: 
  - pip install -r requirements.txt
  - python ./setup.py install
script: 
  - pqshell < .travis/pqshell.cmds
