language: python
python:
  - 2.6
  - 2.7
before_install:
  - apt-get install -y postfix
  - echo 'smtpd_sender_restrictions = regexp:/etc/postfix/sender_restriction' >> /etc/postfix/main.cf
  - cp .travis/postfix/sender_restriction /etc/postfix/
  - cp samples/* /var/spool/postfix/hold/
install: 
  - pip install -r requirements.txt
  - python ./setup.py install
script: 
  - pqshell < .travis/pqshell.cmds
